// File generated by FlutterFire CLI (run: dart run flutterfire_cli:flutterfire configure).
// Replace this file with the output of the command above to use your Firebase project config.

import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    return android;
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA1RwMJrAoyICKxkCdvE5KAJPgmtC3NByY',
    appId: '1:875926263550:android:926b5e98ba64de4d4f77af',
    messagingSenderId: '875926263550',
    projectId: 'near-radio-dca41',
    storageBucket: 'near-radio-dca41.firebasestorage.app',
  );
}
